import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useStore } from '@/lib/store';
import { syncIntegrationKeysToServer } from '@/lib/integrationKeys';
import { CheckCircle2, Key } from 'lucide-react';

function readKeyValue(stored) {
  if (!stored) return '';
  if (typeof stored === 'string') return stored.trim();
  return (stored.apiKey || stored.secretKey || stored.token || '').trim();
}

const INTEGRATIONS = [
  { id:'slack',        name:'Slack',        cat:'Team Communication',    icon:'💬', desc:'Send channel messages when app events fire (e.g. deal closed, task overdue).', implemented:true  },
  { id:'salesforce',   name:'Salesforce',   cat:'Customer Operations',   icon:'☁️', desc:'Sync leads and opportunities from generated CRM apps.', implemented:true  },
  { id:'hubspot',      name:'HubSpot',      cat:'Revenue Workflows',     icon:'🔶', desc:'Update contacts and deal stages from workflow triggers.', implemented:true  },
  { id:'gmail',        name:'Gmail',        cat:'Automated Email',       icon:'✉️', desc:'Send order confirmations, alerts, and onboarding emails.', implemented:true  },
  { id:'notion',       name:'Notion',       cat:'Knowledge & Workspaces',icon:'📄', desc:'Create pages and database rows from app events.', implemented:true  },
  { id:'gsheets',      name:'Google Sheets',cat:'Live Spreadsheet Data', icon:'📊', desc:'Append rows when records are created or updated.', implemented:true  },
  { id:'twilio',       name:'Twilio',       cat:'Customer Messaging',    icon:'📱', desc:'WhatsApp/SMS alerts (e.g. real estate deal closed).', implemented:true  },
  { id:'stripe',       name:'Stripe',       cat:'Payments',              icon:'💳', desc:'Process payments in e-commerce apps generated by OneAtlas.', implemented:true  },
  { id:'gdrive',       name:'Google Drive', cat:'Documents & Storage',   icon:'📁', desc:'Store exports and generated documents.', implemented:true  },
  { id:'webhook',      name:'Webhook',      cat:'Universal',             icon:'🔗', desc:'POST signed payloads to any URL on app triggers.', implemented:true  },
  { id:'jira',         name:'Jira',         cat:'Dev Workflow',          icon:'🔵', desc:'Create issues from engineering task apps.', implemented:false },
  { id:'github',       name:'GitHub',       cat:'Code Workflow',         icon:'🐙', desc:'Open issues from generated dev workflows.', implemented:false },
  { id:'airtable',     name:'Airtable',     cat:'Data & Operations',     icon:'🟦', desc:'Sync rows to Airtable bases.', implemented:false },
  { id:'resend',       name:'Resend',       cat:'Transactional Email',   icon:'📨', desc:'Send typed transactional emails.', implemented:false },
  { id:'discord',      name:'Discord',      cat:'Community',             icon:'🎮', desc:'Post to Discord channels on events.', implemented:false },
];

export default function IntegrationsPage() {
  const integrationKeys = useStore(s => s.integrationKeys);
  const setIntegrationKey = useStore(s => s.setIntegrationKey);
  const removeIntegrationKey = useStore(s => s.removeIntegrationKey);
  const [filter, setFilter] = useState('all');
  const [editingId, setEditingId] = useState(null);
  const [draftKey, setDraftKey] = useState('');

  useEffect(() => {
    fetch('/api/integration-settings')
      .then(r => r.json())
      .then(d => {
        if (d?.integrations) {
          for (const row of d.integrations) {
            if (row.configured && row.masked) {
              /* server only returns masked — keep local keys */
            }
          }
        }
      })
      .catch(() => {});
  }, []);

  const isConnected = (id) => !!readKeyValue(integrationKeys[id]);
  const connectedCount = INTEGRATIONS.filter(i => isConnected(i.id)).length;

  const shown = INTEGRATIONS.filter(i => filter === 'all' || isConnected(i.id));

  const connect = async (id) => {
    if (editingId === id) {
      if (draftKey.trim()) {
        const trimmed = draftKey.trim();
        let normalized = { apiKey: trimmed };
        if (id === 'stripe') {
          if (trimmed.startsWith('sk_')) normalized = { secretKey: trimmed, apiKey: trimmed };
          else if (trimmed.startsWith('pk_')) normalized = { publishableKey: trimmed };
          else normalized = { apiKey: trimmed };
        }
        setIntegrationKey(id, normalized);
        await syncIntegrationKeysToServer({ ...integrationKeys, [id]: normalized });
      }
      setEditingId(null);
      setDraftKey('');
      return;
    }
    setEditingId(id);
    setDraftKey(readKeyValue(integrationKeys[id]));
  };

  const disconnect = (id) => {
    removeIntegrationKey(id);
    setEditingId(null);
    setDraftKey('');
  };

  return (
    <div className="h-full flex flex-col" style={{ background: '#F5F5EE' }}>
      <div className="flex-1 overflow-auto px-8 pt-8 pb-8">
        <div className="flex items-start justify-between mb-6">
          <div>
            <h1 className="font-bold mb-1" style={{ fontSize: 28, color: '#111111', letterSpacing: '-0.02em' }}>Integrations</h1>
            <p className="text-sm" style={{ color: '#6B7280' }}>
              {connectedCount} connected · Integrations are declared when you build (mention Slack, Stripe, Gmail in your prompt).
            </p>
          </div>
          <div className="flex items-center rounded-xl border overflow-hidden" style={{ borderColor: '#E5E7EB' }}>
            {[['all', 'All'], ['connected', 'Connected']].map(([v, l]) => (
              <button key={v} onClick={() => setFilter(v)}
                className="px-4 py-2 text-sm font-bold transition-all"
                style={{ background: filter === v ? '#FF6600' : '#FFFFFF', color: filter === v ? '#FFFFFF' : '#6B7280' }}>
                {l}
              </button>
            ))}
          </div>
        </div>

        <div className="p-4 rounded-2xl border mb-8 flex items-start gap-3" style={{ background: '#FFF3EB', borderColor: '#FFD0A6' }}>
          <Key size={18} style={{ color: '#FF6600', flexShrink: 0, marginTop: 2 }} />
          <div>
            <p className="text-sm font-bold mb-1" style={{ color: '#C05500' }}>How integrations work</p>
            <p className="text-xs" style={{ color: '#92400E', lineHeight: 1.6 }}>
              OneAtlas adds integration hooks to your AppSpec when you mention them in a build prompt.
              Generated apps include workflow stubs that simulate actions in preview.
              To run live calls, paste provider API keys here (or in each app&apos;s admin panel after opening a project).
              <strong> Stripe:</strong> use secret key <code>sk_test_…</code> for server workflows; <code>pk_test_…</code> is publishable (browser only).
              Mention <strong>Stripe</strong> in your build prompt, then open the generated app&apos;s <strong>Payments</strong> page in preview.
              AI provider keys are separate — <Link to="/app/settings" style={{ color: '#FF6600', fontWeight: 700 }}>Settings → API Keys</Link>.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {shown.map(intg => {
            const isConn = isConnected(intg.id);
            const isEditing = editingId === intg.id;
            return (
              <div key={intg.id} className="rounded-2xl border overflow-hidden transition-all"
                style={{ background: '#FFFFFF', borderColor: isConn ? '#FFD0A6' : '#E5E7EB', borderWidth: isConn ? 1.5 : 1 }}>
                <div className="p-5">
                  <div className="flex items-center gap-3 mb-3">
                    <div className="w-12 h-12 rounded-2xl flex items-center justify-center text-2xl" style={{ background: '#F5F5EE' }}>
                      {intg.icon}
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-base" style={{ color: '#111111' }}>{intg.name}</span>
                        {isConn && <CheckCircle2 size={14} style={{ color: '#16A34A' }} />}
                        {!intg.implemented && (
                          <span className="text-[9px] font-bold px-1.5 py-0.5 rounded" style={{ background: '#F1F5F9', color: '#9CA3AF' }}>COMING SOON</span>
                        )}
                      </div>
                      <p className="text-xs" style={{ color: '#9CA3AF' }}>{intg.cat}</p>
                    </div>
                  </div>
                  <p className="text-sm mb-4" style={{ color: '#6B7280', lineHeight: 1.55 }}>{intg.desc}</p>
                  {isEditing && (
                    <input value={draftKey} onChange={e => setDraftKey(e.target.value)}
                      placeholder={intg.id === 'stripe' ? 'sk_test_… (secret) or pk_test_… (publishable)' : `Paste ${intg.name} API key / token`}
                      className="w-full text-xs px-3 py-2 rounded-xl border mb-3 outline-none"
                      style={{ borderColor: '#FF6600', background: '#F9F9F6' }} />
                  )}
                  <div className="flex gap-2">
                    {isConn && !isEditing ? (
                      <>
                        <button onClick={() => connect(intg.id)} className="flex-1 py-2.5 rounded-xl font-bold text-sm border" style={{ borderColor: '#FFD0A6', color: '#FF6600' }}>Edit key</button>
                        <button onClick={() => disconnect(intg.id)} className="flex-1 py-2.5 rounded-xl font-bold text-sm" style={{ background: '#FEE2E2', color: '#DC2626' }}>Disconnect</button>
                      </>
                    ) : (
                      <button onClick={() => connect(intg.id)} disabled={!intg.implemented}
                        className="w-full py-2.5 rounded-xl font-bold text-sm transition-all"
                        style={{ background: intg.implemented ? '#FF6600' : '#E5E7EB', color: intg.implemented ? '#FFFFFF' : '#9CA3AF' }}>
                        {isEditing ? 'Save key' : 'Connect'}
                      </button>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {shown.length === 0 && (
          <div className="text-center py-16">
            <p className="text-sm" style={{ color: '#9CA3AF' }}>No connected integrations yet.</p>
          </div>
        )}
      </div>
    </div>
  );
}
