import type { Integration, IntegrationType } from "@/types";

export const INTEGRATION_REGISTRY: Integration[] = [
  {
    id: "slack",
    name: "Slack",
    category: "Team Communication",
    description: "Send channel messages, DMs, and formatted blocks with action buttons",
    icon: "💬",
    connected: false,
  },
  {
    id: "salesforce",
    name: "Salesforce",
    category: "Customer Operations",
    description: "Create/update Lead, Contact, Opportunity, Account via REST",
    icon: "☁️",
    connected: false,
  },
  {
    id: "hubspot",
    name: "HubSpot",
    category: "Revenue Workflows",
    description: "Update contact, add to sequence, update deal stage",
    icon: "🔶",
    connected: false,
  },
  {
    id: "gmail",
    name: "Gmail",
    category: "Automated Email",
    description: "Send emails, create calendar events, update Google Sheets",
    icon: "📧",
    connected: false,
  },
  {
    id: "notion",
    name: "Notion",
    category: "Knowledge & Workspaces",
    description: "Create pages, append blocks, update database rows",
    icon: "📝",
    connected: false,
  },
  {
    id: "google_sheets",
    name: "Google Sheets",
    category: "Live Spreadsheet Data",
    description: "Append rows, update cells, create new sheet tabs",
    icon: "📊",
    connected: false,
  },
  {
    id: "twilio",
    name: "Twilio",
    category: "Customer Messaging",
    description: "Send WhatsApp templates, SMS notifications, OTP flows",
    icon: "📱",
    connected: false,
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "Payments",
    description: "Create customers, charges, manage subscriptions and refunds",
    icon: "💳",
    connected: false,
  },
  {
    id: "google_drive",
    name: "Google Drive",
    category: "Documents & Storage",
    description: "Store files, sync exports, manage app-generated documents",
    icon: "📁",
    connected: false,
  },
  {
    id: "jira",
    name: "Jira",
    category: "Dev Workflow",
    description: "Create issues, update status, add comments, assign users",
    icon: "🔷",
    connected: false,
  },
  {
    id: "github",
    name: "GitHub",
    category: "Code Workflow",
    description: "Create issues, comment on PRs, trigger workflow dispatch",
    icon: "🐙",
    connected: false,
  },
  {
    id: "airtable",
    name: "Airtable",
    category: "Data & Operations",
    description: "Create rows, update fields, trigger automations",
    icon: "🗃️",
    connected: false,
  },
  {
    id: "resend",
    name: "Resend",
    category: "Transactional Email",
    description: "Send typed transactional emails with templates",
    icon: "✉️",
    connected: false,
  },
  {
    id: "webhook",
    name: "Webhook",
    category: "Universal",
    description: "POST signed payload to any configured URL",
    icon: "🔗",
    connected: false,
  },
  {
    id: "discord",
    name: "Discord",
    category: "Community",
    description: "Post to channels, DM users, update roles",
    icon: "🎮",
    connected: false,
  },
];

export const getIntegrationById = (id: IntegrationType) =>
  INTEGRATION_REGISTRY.find((i) => i.id === id);
